name: FE check

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
      - name: install dependencies
        working-directory: ./skin-resque-frontend
        run: |
          npm cache clean
          rm -rf node_modules
          npm install
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
      - name: install dependencies
        working-directory: ./skin-resque-frontend
        run:
          npm install
      - name: Run ESLint
        working-directory: ./skin-resque-frontend
        run: 
          npm run lint:check
  prettier:
      name: Run prettier
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18.7.0
        - name: install dependencies
          working-directory: ./skin-resque-frontend
          run:
            npm install
        - name: Run ESLint
          working-directory: ./skin-resque-frontend
          run: 
            npm run check:format         
